// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user by email or phone and password, and creates a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in a user",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AuthUser"
                        }
                    },
                    "400": {
                        "description": "invalid request body or credentials",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Terminates the current user session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Protected. Returns the full profile of the authenticated user for the current session, including the linked property when the caller is a tenant. Per business requirements this should also trigger an autobilling check; note: autobilling is not implemented yet in this API version, so only profile data is returned for now.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Me"
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Protected. Partially updates the authenticated user's personal data, including changing the password. Only the provided fields are changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update account settings",
                "parameters": [
                    {
                        "description": "Profile fields to update",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Profile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid request body or email already registered",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user (landlord or tenant) and immediately logs them in, setting the session cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AuthUser"
                        }
                    },
                    "400": {
                        "description": "invalid request body, invalid role, or email already registered",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/properties": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns all properties owned by the currently authenticated user, so a landlord can see their full property portfolio. Only properties the caller owns are returned; other landlords' properties are never exposed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "List properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Property"
                            }
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/properties/property": {
            "post": {
                "description": "Creates a new rental property for a landlord",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "Create a property",
                "parameters": [
                    {
                        "description": "Property data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Property"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.Property"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "landlord not found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "409": {
                        "description": "property already exists",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/properties/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a single property by ID. The property must belong to the authenticated landlord; a property owned by another landlord is reported as not found, so ownership can never be probed via this endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "Get a property",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Property"
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "property not found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Protected, Landlord only. Updates a property's characteristics and utility tariffs (address, area details, hot/cold water and electricity tariffs). Accepts the same payload shape as property creation. Only the owning landlord may edit their property.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "Update a property",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Property data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Property"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "property not found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Protected, Landlord only. Permanently deletes a property. Per business requirements this should also automatically terminate any linked rental contracts and clear the rental reference for bound tenants; note that contract/tenancy linkage does not exist yet in this API version, so only the property record itself is removed for now. Only the owning landlord may delete their property.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "Delete a property",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "property not found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Property": {
            "type": "object",
            "properties": {
                "apartment": {
                    "type": "string",
                    "example": "45"
                },
                "balance": {
                    "type": "number",
                    "example": 1250.75
                },
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "coordinates": {
                    "type": "string",
                    "example": "55.751244,37.618423"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "el1_tariff": {
                    "type": "number",
                    "example": 5.7
                },
                "el2_tariff": {
                    "type": "number",
                    "example": 4.9
                },
                "gvs_tariff": {
                    "type": "number",
                    "example": 189.5
                },
                "house": {
                    "type": "string",
                    "example": "12"
                },
                "hvs_tariff": {
                    "type": "number",
                    "example": 45.2
                },
                "id": {
                    "type": "string",
                    "example": "7c9e6b4a-4321-4a1b-8def-abcdef123456"
                },
                "landlord_id": {
                    "type": "string",
                    "example": "3f7e2b1a-1234-4c56-9abc-1234567890ab"
                },
                "name": {
                    "type": "string",
                    "example": "Sunny Apartment"
                },
                "region": {
                    "type": "string",
                    "example": "Moscow"
                },
                "street": {
                    "type": "string",
                    "example": "Tverskaya"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ivan.petrov@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "strongPass123"
                }
            }
        },
        "request.Profile": {
            "type": "object",
            "properties": {
                "document": {
                    "type": "string",
                    "example": "4510 123456"
                },
                "email": {
                    "type": "string",
                    "example": "newemail@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivan Kolesnikov"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "newSuperSecurePassword"
                },
                "paymentCard": {
                    "type": "string",
                    "example": "1111222233334444"
                },
                "phone": {
                    "type": "string",
                    "example": "+79997776655"
                }
            }
        },
        "request.Property": {
            "type": "object",
            "required": [
                "apartment",
                "city",
                "coordinates",
                "el1_tariff",
                "gvs_tariff",
                "house",
                "hvs_tariff",
                "landlord_id",
                "name",
                "region",
                "street"
            ],
            "properties": {
                "apartment": {
                    "type": "string",
                    "example": "45"
                },
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "coordinates": {
                    "type": "string",
                    "example": "55.751244,37.618423"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "el1_tariff": {
                    "type": "number",
                    "example": 5.7
                },
                "el2_tariff": {
                    "type": "number",
                    "example": 4.9
                },
                "gvs_tariff": {
                    "type": "number",
                    "example": 189.5
                },
                "house": {
                    "type": "string",
                    "example": "12"
                },
                "hvs_tariff": {
                    "type": "number",
                    "example": 45.2
                },
                "landlord_id": {
                    "type": "string",
                    "example": "3f7e2b1a-1234-4c56-9abc-1234567890ab"
                },
                "name": {
                    "type": "string",
                    "example": "Sunny Apartment"
                },
                "region": {
                    "type": "string",
                    "example": "Moscow"
                },
                "street": {
                    "type": "string",
                    "example": "Tverskaya"
                }
            }
        },
        "request.Register": {
            "type": "object",
            "required": [
                "email",
                "initialRole",
                "name",
                "password",
                "phone"
            ],
            "properties": {
                "document": {
                    "type": "string",
                    "example": "4510 123456"
                },
                "email": {
                    "type": "string",
                    "example": "ivan.petrov@example.com"
                },
                "initialRole": {
                    "type": "string",
                    "enum": [
                        "landlord",
                        "tenant"
                    ],
                    "example": "landlord"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivan Petrov"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "strongPass123"
                },
                "paymentCard": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "phone": {
                    "type": "string",
                    "example": "+79161234567"
                }
            }
        },
        "response.AuthUser": {
            "description": "Краткая информация о пользователе, возвращаемая при регистрации и входе.",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ivanov@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "user-a9b8c7d"
                },
                "name": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "role": {
                    "type": "string",
                    "example": "tenant"
                }
            }
        },
        "response.Error": {
            "description": "Стандартный формат ошибки API",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "response.Me": {
            "description": "Полный профиль авторизованного пользователя текущей сессии.",
            "type": "object",
            "properties": {
                "document": {
                    "type": "string",
                    "example": "Паспорт РФ 4512 № 345678"
                },
                "email": {
                    "type": "string",
                    "example": "ivanov@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "user-a9b8c7d"
                },
                "name": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "paymentCard": {
                    "type": "string",
                    "example": "4276111122223333"
                },
                "phone": {
                    "type": "string",
                    "example": "+79991112233"
                },
                "role": {
                    "type": "string",
                    "example": "tenant"
                },
                "tenantPropertyId": {
                    "type": "string",
                    "example": "prop-z8y7x6w"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Session cookie set on successful login",
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Potom Pridumaem API",
	Description:      "API for managing rental properties, landlords, and tenants",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
