// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user by email and password, and creates a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in a user",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Terminates the current user session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out a user",
                "responses": {
                    "204": {
                        "description": "session terminated successfully"
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the user ID and role from the current session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "not authenticated",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user (landlord, tenant, or admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Register"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "invalid request body or role",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "409": {
                        "description": "user already exists",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/properties/property": {
            "post": {
                "description": "Creates a new rental property for a landlord",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "Create a property",
                "parameters": [
                    {
                        "description": "Property data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Property"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.Property"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "landlord not found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "409": {
                        "description": "property already exists",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Property": {
            "type": "object",
            "properties": {
                "apartment": {
                    "type": "string",
                    "example": "45"
                },
                "balance": {
                    "type": "number",
                    "example": 1250.75
                },
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "coordinates": {
                    "type": "string",
                    "example": "55.751244,37.618423"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "el1_tariff": {
                    "type": "number",
                    "example": 5.7
                },
                "el2_tariff": {
                    "type": "number",
                    "example": 4.9
                },
                "gvs_tariff": {
                    "type": "number",
                    "example": 189.5
                },
                "house": {
                    "type": "string",
                    "example": "12"
                },
                "hvs_tariff": {
                    "type": "number",
                    "example": 45.2
                },
                "id": {
                    "type": "string",
                    "example": "7c9e6b4a-4321-4a1b-8def-abcdef123456"
                },
                "landlord_id": {
                    "type": "string",
                    "example": "3f7e2b1a-1234-4c56-9abc-1234567890ab"
                },
                "name": {
                    "type": "string",
                    "example": "Sunny Apartment"
                },
                "region": {
                    "type": "string",
                    "example": "Moscow"
                },
                "street": {
                    "type": "string",
                    "example": "Tverskaya"
                }
            }
        },
        "entity.Role": {
            "type": "string",
            "enum": [
                "landlord",
                "tenant",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleLandlord",
                "RoleTenant",
                "RoleAdmin"
            ]
        },
        "entity.User": {
            "description": "Основная модель пользователя: арендодатель, арендатор или администратор.",
            "type": "object",
            "properties": {
                "document": {
                    "type": "string",
                    "example": "4510 123456"
                },
                "email": {
                    "type": "string",
                    "example": "ivan.petrov@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "3f7e2b1a-1234-4c56-9abc-1234567890ab"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan Petrov"
                },
                "payment_card": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "phone": {
                    "type": "string",
                    "example": "+79161234567"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Role"
                        }
                    ],
                    "example": "landlord"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ivan.petrov@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "strongPass123"
                }
            }
        },
        "request.Property": {
            "type": "object",
            "required": [
                "apartment",
                "city",
                "coordinates",
                "el1_tariff",
                "gvs_tariff",
                "house",
                "hvs_tariff",
                "landlord_id",
                "name",
                "region",
                "street"
            ],
            "properties": {
                "apartment": {
                    "type": "string",
                    "example": "45"
                },
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "coordinates": {
                    "type": "string",
                    "example": "55.751244,37.618423"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "el1_tariff": {
                    "type": "number",
                    "example": 5.7
                },
                "el2_tariff": {
                    "type": "number",
                    "example": 4.9
                },
                "gvs_tariff": {
                    "type": "number",
                    "example": 189.5
                },
                "house": {
                    "type": "string",
                    "example": "12"
                },
                "hvs_tariff": {
                    "type": "number",
                    "example": 45.2
                },
                "landlord_id": {
                    "type": "string",
                    "example": "3f7e2b1a-1234-4c56-9abc-1234567890ab"
                },
                "name": {
                    "type": "string",
                    "example": "Sunny Apartment"
                },
                "region": {
                    "type": "string",
                    "example": "Moscow"
                },
                "street": {
                    "type": "string",
                    "example": "Tverskaya"
                }
            }
        },
        "request.Register": {
            "type": "object",
            "required": [
                "document",
                "email",
                "name",
                "password",
                "phone",
                "role"
            ],
            "properties": {
                "document": {
                    "type": "string",
                    "example": "4510 123456"
                },
                "email": {
                    "type": "string",
                    "example": "ivan.petrov@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivan Petrov"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "strongPass123"
                },
                "payment_card": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "phone": {
                    "type": "string",
                    "example": "+79161234567"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "landlord",
                        "tenant",
                        "admin"
                    ],
                    "example": "landlord"
                }
            }
        },
        "response.Error": {
            "description": "Стандартный формат ошибки API",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Session cookie set on successful login",
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Potom Pridumaem API",
	Description:      "API for managing rental properties, landlords, and tenants",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
